# Site settings
title: Laura Nest Wallace
description: Hello
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Laura Nest Wallace
user_description: Laura is a Brooklyn, New York based project management professional and web development specialist. She is available to help with your technical project management, web-development and content editing needs.
email: lauranestwallace@gmail.com
# twitter_username: lorem_ipsum
github_username:  laurawbrooklyn.github.io
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
