title: Hi, I'm Laura. I'm a Brooklyn based project management professional available to help with your technical project needs.  I also do web development too!
description: Hello
url: "https://laurawbrooklyn.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
username: Laura Nest Wallace
user_description: Laura is a Brooklyn, New York based project management professional. She is available to help with IT project management, content editing and web development projects.
email: lauranestwallace@gmail.com
github_username:  laurawbrooklyn.github.io
google-analytics:
  id: ""
exclude: ['package.json', 'src' , 'node_modules']
