title: Laura Nest Wallace
url: "https://laurawbrooklyn.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
username: Laura Nest Wallace
user_description: I'm a Brooklyn based digital project manager available to help with your project needs.  I'm a graduate of the Thinkful Web Development Bootcamp. I also do content editing, freelance web development and non-IT projects.
email: lauranestwallace@gmail.com
github_username:  laurawbrooklyn.github.io
google-analytics:
  id: ""
exclude: ['package.json', 'src' , 'node_modules']
